{
 "title": "Sentinel API Protection Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Total API Requests",
   "type": "stat",
   "description": "Shows how many requests happened in last minute",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(sentinel_requests_total[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Blocked Requests",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(sentinel_blocked_requests_total[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "API Traffic Rate (requests/sec)",
   "type": "timeseries",
   "description": "requests per second\nper endpoint",
   "gridPos": { "h": 13, "w": 8, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum by(route) (rate(sentinel_requests_total[1m]))",
     "legendFormat": "{{route}}"
    }
   ]
  },
  {
   "title": "Blocked Requests Rate",
   "type": "timeseries",
   "description": "blocks per second",
   "gridPos": { "h": 13, "w": 8, "x": 8, "y": 8 },
   "targets": [
    {
     "expr": "sum by(route) (rate(sentinel_blocked_requests_total[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Endpoint Traffic (Last 5 Minutes)",
   "type": "barchart",
   "description": "which endpoint received traffic",
   "gridPos": { "h": 13, "w": 8, "x": 16, "y": 8 },
   "targets": [
    {
     "expr": "sum by(route) (increase(sentinel_requests_total[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Blocked Traffic Ratio",
   "type": "gauge",
   "description": "percentage of traffic blocked",
   "gridPos": { "h": 13, "w": 8, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(sentinel_blocked_requests_total[5m]))\n/\nsum(increase(sentinel_requests_total[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Traffic Spike Detector",
   "type": "gauge",
   "description": "short-term traffic\n÷\nlong-term traffic",
   "gridPos": { "h": 13, "w": 8, "x": 8, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(sentinel_requests_total[30s]))\n/\nsum(rate(sentinel_requests_total[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Blocked Requests per Endpoint",
   "type": "barchart",
   "description": "which endpoint triggered blocking",
   "gridPos": { "h": 13, "w": 8, "x": 16, "y": 21 },
   "targets": [
    {
     "expr": "sum by(route) (increase(sentinel_blocked_requests_total[5m]))",
     "legendFormat": "{{route}}"
    }
   ]
  }
 ]
}